### ISSUE TITLE
Python's triple-quoted strings as comments

### ISSUE THREAD

**Issue by nuno-andre** [codeauroraforum/comment-filter#1]
You are parsing every triple-quoted string in Python as a comment. For example:

```
variable = """here
document
"""
```

will print
```
           """here
document
```
as a comment

and
```
variable =
```
as code.

**Comment by craigez** [comment]
Hi @nuno-andre, Thanks for the feedback. This was intentional, as triple-quoted strings are often used as multi-line comments. Our main use case in developing the library was to capture the comments, rather than then code.

Removing the quotes from the grammar definition or making them optional here: https://github.com/codeauroraforum/comment-filter/blob/master/comment_filter/language.py#L19 would allow you to include these triple-quoted strings in the code output.

**Comment by nuno-andre** [comment]
Hi @craigez! Thanks for your response.

Sure, but this way it wouldn't include triple-quoted string comments (like docstrings) as comments ;)

**Comment by craigez** [comment]
Which behavior did you want for your usage @nuno-andre? Did you want them included as code, comments, both, or optionally handled either way?

**Comment by nuno-andre** [comment]
Any string is a comment in Python as long as it's not assigned, whether triple (like docstrings) or single-quoted like:

```
"i'm a comment"
``` 

I'm actually searching for a library which can make such a distinction. I mean, comment when it's comment and code when it's code ;)

**Comment by nuno-andre** [comment]
I finally wrote [some code](https://gist.github.com/nuno-andre/443c968a678c6f2f6b7650902bebe1ce) (if it could be helpful), but I'll definitely use your code for Java and Go comments. Thank you!

**Comment by craigez** [comment]
Making the distinction between the cases you specify requires parsing the language and building an AST. This library is a bit simpler than that at this time. Glad you found a solution.
